version: '3.0'
services:
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  ingest:
    build:
      context: ./ingest
    env_file: ./ingest/.env
  process:
    build:
      context: ./process
    env_file: ./process/.env
    volumes:
      - redis-data:/data
  influxdb:
    image: 'influxdb'
    volumes:
      - influxdb-data:/var/lib/influxdb
  grafana:
    image: 'grafana/grafana'
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/config.ini
    labes:
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`${GRAFANA_URL}`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.port: 3000
      traefik.docker.network: reverse_proxy

volumes:
  influxdb-data:
  redis-data: