version: '3.0'
services:
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  ingest:
    build:
      context: ./ingest
    depends_on: 
      - redis
    env_file: ./ingest/.env
  process:
    build:
      context: ./process
    depends_on:
      - redis
      - influxdb
    env_file: ./process/.env
    volumes:
      - redis-data:/data
  influxdb:
    image: 'influxdb'
    volumes:
      - influxdb-data:/var/lib/influxdb
  grafana:
    image: 'grafana/grafana'
    depends_on: 
      - influxdb
    ports:
      - 3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - PLUGINS=redis-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/config.ini
    labels:
      traefik.enable: true
      traefik.http.routers.aera_grafana.rule: Host(`${GRAFANA_URL}`)
      traefik.http.services.aera_grafana.loadbalancer.server.port: 3000
      # traefik.port: 3000
      traefik.docker.network: reverse_proxy
    networks:
      - default
     - reverse_proxy

volumes:
  influxdb-data:
  redis-data:

networks:
  reverse_proxy:
    external:
      name: reverse_proxy