apiVersion: 1

datasources:
  - name: 'Redis'
    type: 'redis-datasource'
    org_id: 1
    # access: 'proxy'
    url: 'redis://redis:6379'
    is_default: false
    version: 1
    editable: true
  - name: 'InfluxDB'
    type: 'influxdb'
    access: 'proxy'
    org_id: 1
    url: 'http://influxdb:8086'
    version: 1
    editable: true
    is_default: true
    secureJsonData:
      token: $INFLUX_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: $INFLUX_BUCKET
      tlsSkipVerify: true